### PR TITLE
Deploying laravel to kubernetes v3

### PR DESCRIPTION
**Pull request by danielepolencic**
I had to create another PR because @keithmifsud forked the repo instead of pushing the branch.

The other option was to fork Keith's repo, raise a PR against his repo, merge the first PR and then merge the other PR. Not very friendly.

**Please from now on push the branch to the repo directly.**

This PR should be rebased on top of https://github.com/learnk8s/learnk8s.io/pull/45 or it should supersede it.

Changes:
- Added the main illustration
- Added diagrams and illustrations for
  - service
  - scaling
  - ingress

I tweaked the title. Let me know what you think.

Preview: https://deploy-preview-59--learnk8s.netlify.com/blog/deploying-laravel-to-kubernetes

### CODE REVIEW

**Comment by keithmifsud** [comment]
@danielepolencic The illustrations are great 😃 The title is better as it's more informative. I think I should change the article's publish date? If so I'll do it as soon as you let me know. I can pull these changes and then push to this PR directly (i.e: not from my fork).

**Comment by danielepolencic** [comment]
Yes, please. change the publish date!

**Comment by danielepolencic** [comment]
🎉 🎉 🎉 🎉 

I think we need to tweak the links! there's no description of them, just the link to the article. Is there any way we could pull in the open graph description?

**Comment by keithmifsud** [comment]
Which links?

**Comment by danielepolencic** [comment]
image
image

**Comment by keithmifsud** [comment]
This issue seems to be for twitter only as the rest show the description and the main image too. I'm working on it now as a separate issue and in a separate branch https://github.com/learnk8s/learnk8s.io/issues/60

**Comment by danielepolencic** [comment]
Thanks!

**Pull request merged**
