### PR TITLE
Keith's profile

### PR DESCRIPTION
**Pull request by danielepolencic**

### CODE REVIEW

**Comment by danielepolencic** [comment]
Apparently, it wasn't that simple. `target=_blank` should be paired with `rel=noopener` [according to this article](https://mathiasbynens.github.io/rel-noopener/).

As per the link, how do you want that to work?

**Comment by keithmifsud** [comment]
I never used rel=noopener so far. It's up to you. I assure you that links to my properties will not have any malicious intent :)

I didn't understand what you meant by:
"As per the link, how do you want that to work?"

**Comment by danielepolencic** [comment]
Do you want to amend your bio and append "Keith blogs at [keith-mifsud.me](https://keith-mifsud.me)"? Or did you have something else in mind?

**Comment by keithmifsud** [comment]
Oh I get it :) I thought you'll just put another circled icon to match the existing ones. Would it be okay?

**Comment by danielepolencic** [comment]
Link added. Let me know what you think.

**Comment by keithmifsud** [comment]
All good thanks. I pulled it locally and all looks fine.

**Pull request merged**
