### PR TITLE
Wrote article about installing :whale: and k8s on windows.

### PR DESCRIPTION
**Pull request by keithmifsud**
@danielepolencic Please review this 2nd post :)

Once we move forward with Grammarly, I might cancel these PRs and resubmit new ones.

### CODE REVIEW

**Comment by danielepolencic** [comment]
Quick note so I don't forget. You could have at the end of the article comparing different installation methods as seen in http://cs.mcgill.ca/~mxia3/2018/02/18/Five-different-Rails-development-environment-on-Windows-10-and-their-pros-and-cons/

Note sure how this is relevant to us, unless we have 2-3 options.

**Comment by keithmifsud** [comment]
@danielepolencic Not sure to which installation you are suggesting I add more options? 

There are 2 options for Docker. I mentioned them both BUT I would still use the Toolbox even on a PC which meets the requirements for "Docker for Windows" because that prohibits the use of any other Hyper-V software and most devs will use VB or VMWare for other jobs at the same time. 

As an example, even I set up a Docker Image with all the containers I need for an application (Http, MySQl etc...) I might still need VB to test other integrations that do not form part of the deployment. Such as an IOT gateway or an MQTT emulator. Meaning, to use Hyper-V in windows you must not need VB or VMWare which is unlikely for most devs.

The only option I left out is the ability to install Kubectl using Chocolatey. This is intentional. I didn't want to add commercial dependencies so that everyone can install on Windows without having to purchase the package manager which is expensive and not needed by any other dev tools. I don't see any point of anyone buying chocolatey to install Kubectl and I never seen any other application which could benefit from Choco.

Are there other options that I missed?

**Comment by danielepolencic** [comment]
I understand your point about using docker toolbox. However, I think the article is about the options you have when it comes to Docker on Windows. You can make a recommendation, but I think you should list them all. The new Docker for windows comes with Kubernetes pre-installed. I think that could be a good option for a lot of people.

I thought Chocolatey was free?

**Comment by keithmifsud** [comment]
@danielepolencic is someone reviewing this post? I cannot add Lewis!

**Comment by danielepolencic** [comment]
@denhamparry do you mind reviewing the content since you had to go through the pain of setting up Docker + k8s on Win recently?

Also, I'd like to add Chocolatey as an option even if it's a commercial option. I believe Lewis used it to install his deps.

**Comment by denhamparry** [comment]
I'll have a look at this tomorrow!

**Comment by danielepolencic** [comment]
@denhamparry did you install your dependencies with Chocolatey?

**Comment by danielepolencic** [comment]
I tried to install Docker on my Windows VM on Parallels. It was awful.

Notes:

- To find out which version of Windows your PC is running, press Windows logo key  + R, type `winver`, then select OK.
- When you run on a not supported version of Windows:
    - [“Installation failed: one pre-requisites is not fulfilled. Docker for Windows requires Windows 10 Pro or Enterprise version 14393, or Windows server 2016 RTM to run”](https://www.dropbox.com/s/q4xhtqoq1zbagdt/Screenshot%202018-04-25%2021.19.07.png?dl=0)
- Docker for Windows requires Microsoft Hyper-V to run. The Docker for Windows installer enables Hyper-V for you, if needed, and restart your machine. After Hyper-V is enabled, VirtualBox no longer works, but any VirtualBox VM images remain. VirtualBox VMs created with docker-machine (including the default one typically created during Toolbox install) no longer start. These VMs cannot be used side-by-side with Docker for Windows. However, you can still use docker-machine to manage remote VMs. [What to know before you install](https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install)
- More about Docker for Windows & VirtualBox: https://nickjanetakis.com/blog/docker-tip-13-get-docker-for-windows-and-virtualbox-working-together
- Enabling/Disabling Hyper-V: https://stackoverflow.com/questions/40253414/cohabitation-docker-virtualbox-on-windows
- [“This computer doesn’t have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory”](https://www.dropbox.com/s/8ned7232p07nbat/Screenshot%202018-04-25%2021.29.07.png?dl=0) Enable it in BIOS
- After binding ports in Docker, you visit `<docker machine ip>:<port>` and are greeted by [“Hmmm...can’t reach this page”](https://www.dropbox.com/s/5bvvklhzetqwjcc/Screenshot%202018-04-25%2022.03.33.png?dl=0) On Edge you can’t access local IPs because… [reasons](https://stackoverflow.com/questions/31735700/microsoft-edge-is-not-opening-http-192-168-0-1 ). We should use Chrome only.

My Windows PRO license isn't working. As soon as I get a new one I'll try to install the newer version of Docker.

As things stands, we should recommend Windows user to use minikube as their remote Docker daemon. Developer experience is awful.

**Comment by keithmifsud** [comment]
@danielepolencic I'm not sure where we are with this post. Sorry, I was away and lost track. Please correct if I'm wrong, you'd like me to add Chocolatey and Docker for Windows on top of the current options. Correct?

**Comment by danielepolencic** [comment]
We should revamp this article with the trade-offs and common errors. I haven't finished my evaluation, but this is the outline I'm proposing:

- Intro
- Challenges on Docker and k8s for windows
  - how to run Linux and Windows containers
- Options if you have Windows Home or Student
  - If you're running only Docker
    - Docker Toolbox
      - how to install Docker toolbox
  - If you're running Docker and Kubernetes
    - minikube
      - how to install minikube
    - how to install Minikube and Docker cli
        - manually
        - Chocolatey
- Options if you have Windows Pro
    - If you're running only Docker
      - Docker for Windows
        - how to install Docker for Windows
    - If you're running Docker and Kubernetes
      - Docker for Windows
        - how to install Docker for Windows  
      - minikube
        - How to install minikube
        - Using minikube with Hyper-V

I'm waiting for my License key to confirm the bottom half. I'm thinking that perhaps we should create a diagram like this:

image

**Comment by danielepolencic** [comment]
I think as an intro image, we could have a variation of those:

- https://www.istockphoto.com/gb/vector/tools-of-carpenter-gm528616100-93064199
- https://www.istockphoto.com/gb/vector/property-investor-gm464762352-59235848
- https://www.istockphoto.com/gb/vector/businessman-bitcoin-mining-concept-gm892611604-247026136

**Comment by keithmifsud** [comment]
The best of 3 images IMO is the carpenter's tools. I don't see the 3rd one relevant and I don't understand the 2nd 🤔

**Comment by keithmifsud** [comment]
like the diagram idea 🤕

**Comment by keithmifsud** [comment]
Content-wise... this will probably end up being a re-write as we did with the laravel one as I was learning while writing. I think I should wait for @danielepolencic full review first?

**Comment by danielepolencic** [comment]
- added diagram
- new outline proposed

**Comment by danielepolencic** [comment]
I had a go at it. Rough first incomplete pass:

---

## Intro

[TODO: Intro]

## What are the trade-offs/challenges of installing Docker and Kubernetes on Windows

When it comes to installing Docker on Windows, you have few options.

If you're running Windows 10 Home or Student edition, you won't be able to run the newer versions of Docker for Windows.
This isn't Docker fault, though. The people at Docker did tremendous good work in porting containers to the Windows platform. And when they picked the technology to virtualise containers, they opted for Hyper-V since it's the native hypervisor in Windows. The benefit is crystal clear: smooth butter performance.
Unfortunately not all Windows versions ship with Hyper-V hypervisor. If you're using Windows 10 Home or Student edition, you are out of luck. You won't be able to install and run Docker for Windows.
But worry not! You can still run Docker Toolbox - a virtual machine with Docker installed. You won't reach the same speed as Docker for Windows, but you can download and similarly run containers.

At this point, you may think that Docker for Windows is the answer if you're running on Windows 10 Pro. You have the latest Docker, excellent performance and polished user experience.
There's something else, though.
The hypervisor used by Docker for Windows is extremely powerful - indeed it's called a Type-1 hypervisor. It's so powerful that it doesn't play nicely with weaker hypervisor such as the one in VirtualBox - or Type-2 hypervisors. You can't have Type-1 and Type-2 hypervisors running at the same time on your machine. Or in other words, if you enable and run Docker for Windows, you won't be able to launch and play with your virtual machines on VirtualBox.
Depending on your setup, this may be a smaller issue. Maybe you're fully committed to the containerised world.
But if you're still relying on managing virtual machines with tools such as Vagrant, perhaps you should be aware of the annoyance. You can enable and disable the Hyper-V hypervisor at will, but it requires a restart.

If you're frequently switching from containers to virtual machines, perhaps Docker Toolbox is a more convenient choice.

Lastly, if you're interested in running Windows container - aka containers with a base image that inherits from Windows - Docker for Windows is the only option. And you will need Windows 10 Pro or Enterprise for that.

## What about Kubernetes

If you want to run Kubernetes locally, the most accessible choice is Minikube.

Minikube is a virtual machine running on an embedded Linux Distribution (Buildroot) and comes with the Docker daemon pre-installed. It's Kubernetes batteries included.
Minikube can run its virtual machine on VirtualBox or Hyper-V - [there are more options too](#missing-link).
Which is great news because if you decide to use Hyper-V, you should use the Hyper-V driver fro minikube and avoid restarting your laptop every time you want to test container locally or deploy to Kubernetes.

That's a lot of choices and trade-offs, so here's a summary of what we discussed:

r

## 1. Installing Docker and Kubernetes on Windows 10 Pro

### Docker

You can download Docker for Windows [from the official website](https://www.docker.com/docker-windows). The installation is straightforward. What happens next is less so. In fact, be aware that you should have VT-X/AMD-v enabled before you run Docker for Windows. Depending on your computer, you may need to reboot and enable it in your BIOS.

If you're unsure about VT-X/AMD-v being enabled, don't worry. If you don't have it, you will be greeted with the following error message:

```text
This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
```

Another common error has to do with the Hyper-V hypervisor not being enabled. If you experience this error:

```text
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.
```

You should enable Hyper-V. Open a new command prompt as an administrator and type the following:

```bash
bcdedit /set hypervisorlaunchtype auto
```

You should reboot your machine and Docker should finally work. But how do you know if Docker is working?

Open a new command prompt and type:

```bash
docker ps
```

If everything works as expected, you should see an empty list of containers running. If your Docker daemon isn't running, you're probably banging your head against this error:

```text
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

The error above is suggesting that your Docker installation is not behaving normally and wasn't able to start correctly.

> Please note that you won't be able to complete the Wordpress installation because there's no database.

### Minikube on Hyper-V

You can download minikube's installer from the [official Github repository](https://github.com/kubernetes/minikube/releases). And installing minikube should not raise any issue.

It's usually a good idea to have the minikube executable in your path.

[Instructions on how to add C:\Program Files (x86)\Kubernetes\Minikube to your path].

Before we start the cluster, there's one more task you have to complete. Minikube on Hyper-V needs an external network switch.

[Instruction on how to create an external network switch in Hyper-V Manager https://docs.docker.com/machine/drivers/hyper-v/]

If you fail to create the network switch, you will see the following error when you start minikube:

```text
E0427 09:06:16.000298    3252 start.go:159] Error starting host: Error creating host: Error executing step: Running precreate checks.
: no External vswitch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/.
```

You can test your minikube installation with:

```bash
minikube start --vm-driver=hyperv --memory=2048
```

> Please note that `--vm-driver=hyperv --memory=2048` are necessary only for the first start. If you wish to change the driver or the memory you have to `minikube destroy` and recreate the VM with the new settings.

If for any reason minikube fails to start up, you can debug it with:

```bash
minikube delete
minikube start --vm-driver=hyperv --memory=2048 --v=7 --alsologtostderr
```

The extra verbose logging should help you get to the issue. In my particular case, minikube used to fail with:

```text
E0427 09:19:10.114873   10012 start.go:159] Error starting host: Error starting stopped host: exit status 1.
```

Not very helpful. After enabling verbose logging the issue was more obvious:

```text
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM
```

I was running out of memory!

It's time to test if you're installation is successful. In the command prompt type:

```bash
kubectl get nodes
```

You should be able to see a single node in Kubernetes.

### VirtualBox

[TODO: turning Hyper-V off every time you wish to run VirtualBox]

## 2. Installing Docker on Windows 10 Home

[TODO: Docker toolbox]
[TODO: Docker architecture client-server]

## 3. Installing Docker and Kubernetes on Windows 10 Home

[TODO: Installing Minikube]
[TODO: Installing Docker CLI]
[TODO: Connecting to a remote daemon]

## Testing your Docker installation

A better test is to run Wordpress as a Docker container. In your command prompt type:

```bash
docker run -ti -p 8080:80 wordpress
```

Once Docker has completed downloading all the package, you should visit [http://localhost:8080/](http://localhost:8080/). You should be able to see the Wordpress installation Wizard.

## Testing your Kubernetes cluster installation

### Deployment

### Service

### Dashboard

## Summary

**Pull request closed without merging**
