### PR TITLE
Gh 49 - Share buttons on article pages.

### PR DESCRIPTION
**Pull request by keithmifsud**
@danielepolencic I've submitted this PR so that you can preview it. As I thought, this is no longer possible without JS. Note that the share buttons in use on this link https://simplesharebuttons.com/html-share-buttons/ are not the "simple buttons" but are from "Share This". You can verify this by viewing the page source code.

I don't like how the FB link opens in a full-size window. Also, it does not pull the OG data.

Please let me know how you'd like to proceed.

### CODE REVIEW

**Comment by keithmifsud** [comment]
@danielepolencic After testing the preview I can see that the OG data is being pulled. I can force the window to open in a new tab but I will need JS to open a new window with a smaller size. Is it okay for me to add some JS for this? It will be on the same server.

**Comment by keithmifsud** [comment]
@danielepolencic I'm going to go ahead with using these "simple share buttons" and forcing the window to be smaller with JS. I'll refactor if you disagree later on 😄

**Comment by danielepolencic** [comment]
If we can avoid JS, that would be great! If you think the experience is better than some JS, please go ahead.

**Comment by keithmifsud** [comment]
@danielepolencic I'll refactor to use includes for the svgs 😄 

The mail icon doesn't look like an envelope to me but I still assume it is. Not sure others will. The issue is that on phones, you don't get the tooltip. I can open a separate issue for it and we can get back to it later on as I think the designer is busy.

**Comment by danielepolencic** [comment]
Can we have the links at the bottom (after the article) if you're on mobile?
The designer is me in this case. I can pick it up in 2 weeks time, unfortunately. Create an issue and I'll work on it.

**Comment by keithmifsud** [comment]
@danielepolencic Sorry I should have explained the way I'm working. This PR has a ref of #GH-53 but the branch is named GH-49. Same as the issue #GH-49. If you take a look at the issue, you can see a task list that I followed to accomplish this task. ONe of which is to have the links at the bottom on SM and XS screens. You can test this already, it works similar to medium's (blogging site) buttons. Probably needless to say that if you're testing using the emulator on chrome, you will need to refresh the page for the JS variables to stop thinking it's either a mobile or a desktop device.

Please let me know if you wish for me to change how the links work on smaller screens 😄

**Comment by danielepolencic** [comment]
Oh sorry! I thought you were using only CSS to achieve that. I didn't notice the JS. I think the JS you have is way better than including the fb or twitter sdk. We could refactor some of the html/css to position the buttons with CSS only but we can leave that for another day.

**Comment by keithmifsud** [comment]
@danielepolencic I just pushed an update. All I did is swapped the images (assets) as includes. Will merge this now as all tests have passed.

**Pull request merged**
