### PR TITLE
updated project getting started

### PR DESCRIPTION
**Pull request by danielepolencic**

### CODE REVIEW

**Comment by danielepolencic** [comment]
I'm having a hard time installing Docker inside a VM and I don't have a Windows laptop with me.

I'll try to launch a Windows EC2 instance on Amazon tomorrow. Such a PITA.

**Comment by keithmifsud** [comment]
@danielepolencic I'm looking into this as we speak.

**Comment by danielepolencic** [comment]
I don't have a Windows machine at home and none of the virtualised VM on the market support VT-X AMD-V, so I can't run VirtualBox on them.

From what I understand there're two options to run Docker on Windows:

## 1. You have Windows with Hyper-v enabled such as Windows 10 Pro

Happy days. You should be able to install the latest version of Docker. You can seamlessly map ports from containers to your host.

```bash
$ docker run -p 8080:80 nginx
```

You should be able to visit [http://localhost:8080](http://localhost:8080) and see "Hello Nginx!". This is exactly the same experience as if you were to use Linux or Mac.

## 2. You have an unsupported version of Windows or you don't have Hyper-v

You should fallback to using Docker toolbox. Before we jump on what Docker toolbox is, a quick recap of the Docker architecture. Docker uses a client-server architecture: there's a Docker daemon that builds and runs containers. And there's a client such as the Docker CLI that lets you interact with the daemon. You could have several clients talking to the same Docker daemon. And vice versa.

image

Docker toolbox is a virtual machine that runs a Linux distro with the Docker daemon inside it. The docker CLI is instructed to talk to the daemon inside the VM and every new container you create is created within the VM.

When you launch a container and bind its ports, the ports are bound inside the VM.

```bash
$ docker run -p 8080:80 nginx
```

image

If you try to visit [http://localhost:8080](http://localhost:8080), nothing will appear. This is because the container binds its ports against the VM. You should retrieve the IP address of the VM first:

```bash
$ docker-machine ip
```

And visit the following URL: http://<docker-machine ip>:8080

**Comment by keithmifsud** [comment]
Hi @danielepolencic ,

Sorry I was away yesterday by the time you started!

Anyway, finally fixed it and I can run the site including auto-generation. I think it's quite slow to update compared to normal but at least it works.


I did try to follow your instructions for method #2 above but even if giving the right IP address, in my case http://192.168.99.100:8080, it didn't work. The screen was blank.

Then I found this guy: https://github.com/BretFisher/jekyll-serve

Using QuickStartTerminal from Docker, I simply cdd into the site root and:

`docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve`

It worked but now I'll try to get jekyll-doctor so that I can run --drafts too.

**Comment by keithmifsud** [comment]
@danielepolencic I ended up creating a custom docker image https://hub.docker.com/r/keithmifsud/jekyll-serve/

It works the same as the one mentioned above with the addition of allowing for --drafts.

The readme of my forked repo explains the commands https://github.com/keithmifsud/jekyll-serve

But basically, we can run jekyll inside a docker container:

cd to/wehre/your/_config.yml/exist
docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

and the site is then available on the docker IP (without port number - unless the above command is changed to use a port other than 80)
http://192.168.99.100

To server and watch with drafts:
cd to/wehre/your/_config.yml/exist
docker run -p 80:4000 -v $(pwd):/site -e JEKYLL_DRAFTS=true bretfisher/jekyll-serve

Simples 🥇

**Comment by keithmifsud** [comment]
I cannot check out this branch locally. Not sure why so I cannot update the readme myself.

**Comment by danielepolencic** [comment]
Did you git pull?

**Pull request merged**
