### PR TITLE
Small change Bio/Pics/Navbar

### PR DESCRIPTION
**Pull request by valentin2105**
😄

### CODE REVIEW

**Comment by danielepolencic** [comment]
- I kept the image size slightly larger to compensate for retina displays. Is there a particular reason why you want it smaller?
- The link to the team page is currently in the footer. I kept it that way because we didn't have a proper team and there isn't much screen real estate on iPad/iOS. Do you think it's better to have it on the main menu?

CI is broken. I added you to nelitfy so that you can inspect the build. I suspect this is what you need to change to: "{% link _pages/about-us/index.md %}"

**Comment by valentin2105** [comment]
I have rollback the Team in Navbar, no problem ;)
I have changed the pics to make it right and not leaned.

**Comment by danielepolencic** [comment]
LGTM 👍 feel free to merge!

**Comment by valentin2105** [comment]
I don't think I got the rights access to merge ?

**Comment by danielepolencic** [comment]
You should be able to now?

**Comment by valentin2105** [comment]
BOOM. 😺

**Comment by danielepolencic** [comment]
Thanks!

**Pull request merged**
