### PR TITLE
[wip] Add Chris Nesbitt-Smith bio

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by danielepolencic** [comment]
Image is broken. You should place it in `_pages/about-us`.

Actually, I like Chief rejector of PRs.

**Comment by chrisns** [comment]
sure, but actually what should I put there?

**Comment by danielepolencic** [comment]
Lead {instructor, Technologist Extraordinaire}, Head of TDA/TSG, Kubernetes Specialist, Principal Developer, DevOps with a pink hat.

Pick one or make one.

**Comment by chrisns** [comment]
done, I resisted going for `Innovation sherpa` or `Chief envisioning officer`

**Comment by danielepolencic** [comment]
Innovation sherpa!!!! Oops... Do you mind rebasing?

**Comment by danielepolencic** [comment]
LGTM! Can you merge this? I want to make sure you have permission.

**Pull request merged**
